# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--name', 'salt-hello-world']
    v.customize ['modifyvm', :id, '--memory', 1024]
  end

  config.vm.hostname = 'salt-hello-world'

  config.vm.network :private_network, ip: '111.222.111.222'
end
